[package]
authors = [
  "Diem Association <opensource@diem.org>",
  "Starcoin Core Dev <dev@starcoin.org>",
]
description = "starcoin Move VM code coverage"
edition = "2021"
license = "Apache-2.0"
name = "move-coverage"
publish = false
version = "1.12.5"

[dependencies]
anyhow = "1.0.41"
bcs = "0.1.2"
clap = {version = "3", features = ["derive"]}
codespan = {version = "0.8.0", features = ["serialization"]}
colored = "2.0.0"
petgraph = "0.5.1"
serde = {version = "1.0.130", default-features = false}

move-binary-format = {git = "https://github.com/starcoinorg/move", rev = "40bd57fb3823419e6e48bc08a2483a3f680e7f82"}
move-bytecode-source-map = {git = "https://github.com/starcoinorg/move", rev = "40bd57fb3823419e6e48bc08a2483a3f680e7f82"}
move-command-line-common = {git = "https://github.com/starcoinorg/move", rev = "40bd57fb3823419e6e48bc08a2483a3f680e7f82"}
move-coverage = {git = "https://github.com/starcoinorg/move", rev = "40bd57fb3823419e6e48bc08a2483a3f680e7f82"}
[features]
default = []
